export type Term = {
  id: string;
  term: string;
  ipa: string;
  termEs: string;
  simple: string;
  simpleEs: string;
  example: string;
  cognate?: boolean;
  related?: string[];
};

export const GLOSSARY: Term[] = [
  {
    id: "logo",
    term: "logo",
    ipa: "LOH-goh",
    termEs: "logotipo",
    simple: "A small picture or word that stands for a company, team, or idea.",
    simpleEs: "Una imagen o palabra pequeña que representa una empresa, equipo o idea.",
    example: "The fox crest is the logo for Foxfire Camp.",
    related: ["brand", "mark"],
  },
  {
    id: "brand",
    term: "brand",
    ipa: "brand",
    termEs: "marca",
    simple: "The whole personality of a company — name, colors, voice, and how it treats people. A logo is only one piece.",
    simpleEs: "La personalidad completa de una empresa. El logo es solo una parte.",
    example: "The brand includes the logo, the colors, and the feeling you get.",
  },
  {
    id: "mark",
    term: "mark",
    ipa: "mark",
    termEs: "marca gráfica",
    simple: "The graphic sign itself — the shape you recognize even without words.",
    simpleEs: "La señal gráfica: la forma que reconoces incluso sin palabras.",
    example: "The Stride stroke is a mark. It works even without the company name.",
  },
  {
    id: "wordmark",
    term: "wordmark",
    ipa: "WURD-mark",
    termEs: "logotipo de texto",
    simple: "A logo made from the name, drawn in a special way.",
    simpleEs: "Un logo hecho con el nombre, dibujado de una forma especial.",
    example: "A script that is only the word Quill is a wordmark.",
    related: ["lettermark", "typography"],
  },
  {
    id: "lettermark",
    term: "lettermark",
    ipa: "LET-er-mark",
    termEs: "monograma",
    simple: "A logo made from initials, like two R's in a roundel.",
    simpleEs: "Un logo hecho con iniciales.",
    example: "Red Rail's RR in a circle is a lettermark.",
  },
  {
    id: "pictorial",
    term: "pictorial mark",
    ipa: "pik-TOR-ee-uhl",
    termEs: "marca pictórica",
    simple: "A logo that is a simplified picture of a real thing — a fox, a lantern, a lighthouse.",
    simpleEs: "Un logo que es un dibujo simple de algo real.",
    example: "A fox crest with a flame is a pictorial mark.",
    related: ["abstract"],
  },
  {
    id: "abstract",
    term: "abstract mark",
    ipa: "AB-strakt",
    termEs: "marca abstracta",
    simple: "A logo made of a shape that is not a real object. You learn what it means.",
    simpleEs: "Un logo hecho de una forma que no es un objeto real.",
    example: "Stride's plant-and-launch stroke is an abstract mark.",
    cognate: true,
  },
  {
    id: "combination",
    term: "combination mark",
    ipa: "kom-buh-NAY-shun",
    termEs: "marca combinada",
    simple: "A logo that pairs a symbol with the name so you can use them together or apart.",
    simpleEs: "Un logo que junta un símbolo con el nombre.",
    example: "Summit shows one peak, a flag, and the name — a combination mark.",
    cognate: true,
  },
  {
    id: "emblem",
    term: "emblem",
    ipa: "EM-bluhm",
    termEs: "emblema",
    simple: "A logo where the name sits inside a badge, seal, or shape.",
    simpleEs: "Un logo donde el nombre está dentro de un sello o insignia.",
    example: "Mesa Museum's name inside a badge is an emblem.",
    cognate: true,
  },
  {
    id: "negative-space",
    term: "negative space",
    ipa: "NEG-uh-tiv space",
    termEs: "espacio negativo",
    simple: "The empty area around and inside a shape. Designers use it to hide a second picture.",
    simpleEs: "El área vacía alrededor y dentro de una forma.",
    example: "The arrow between AeroLink's E and R is made of negative space.",
    related: ["positive-space", "figure-ground"],
  },
  {
    id: "positive-space",
    term: "positive space",
    ipa: "POZ-ih-tiv space",
    termEs: "espacio positivo",
    simple: "The ink — the part of the logo that is drawn, not the empty air.",
    simpleEs: "La tinta: la parte dibujada del logo.",
    example: "The letters of a wordmark are positive space.",
  },
  {
    id: "figure-ground",
    term: "figure-ground",
    ipa: "FIG-yer ground",
    termEs: "figura-fondo",
    simple: "Your eye chooses what is the object and what is the background. A smart logo can flip this.",
    simpleEs: "El ojo elige qué es el objeto y qué es el fondo.",
    example: "A leaf with a book cut out uses figure-ground.",
  },
  {
    id: "gestalt",
    term: "gestalt",
    ipa: "geh-SHTALT",
    termEs: "gestalt",
    simple: "The idea that the brain sees a whole, not just parts. We fill in missing pieces.",
    simpleEs: "La idea de que el cerebro ve un todo, no solo partes.",
    example: "Five rings that look locked together use gestalt.",
  },
  {
    id: "contrast",
    term: "contrast",
    ipa: "KON-trast",
    termEs: "contraste",
    simple: "A clear difference — dark next to light, thick next to thin — so the mark is easy to see.",
    simpleEs: "Una diferencia clara para que la marca se vea fácil.",
    example: "White letters on a dark badge have strong contrast.",
    cognate: true,
  },
  {
    id: "balance",
    term: "balance",
    ipa: "BAL-uns",
    termEs: "equilibrio",
    simple: "The feeling that a design is not heavier on one side.",
    simpleEs: "La sensación de que el diseño no está más pesado de un lado.",
    example: "A heavy icon on the left needs the name to balance it on the right.",
  },
  {
    id: "symmetry",
    term: "symmetry",
    ipa: "SIM-uh-tree",
    termEs: "simetría",
    simple: "Both sides match, like a butterfly. It feels calm and official.",
    simpleEs: "Los dos lados coinciden. Se siente calmado y oficial.",
    example: "A target of nested circles is symmetrical.",
    cognate: true,
  },
  {
    id: "simplicity",
    term: "simplicity",
    ipa: "sim-PLIS-ih-tee",
    termEs: "simplicidad",
    simple: "Using only what you need. A simple logo still works when it is tiny.",
    simpleEs: "Usar solo lo necesario. Un logo simple funciona aunque sea diminuto.",
    example: "Stride is simple. A van with 40 windows is not.",
    cognate: true,
  },
  {
    id: "scale",
    term: "scale",
    ipa: "skayl",
    termEs: "escala",
    simple: "How big or small the logo is. It must work on a billboard and on a phone.",
    simpleEs: "Qué tan grande o pequeño es el logo.",
    example: "Test every mark at the size of a fingernail.",
    cognate: true,
  },
  {
    id: "palette",
    term: "palette",
    ipa: "PAL-it",
    termEs: "paleta",
    simple: "The small set of colors a brand uses on purpose.",
    simpleEs: "El conjunto pequeño de colores que una marca usa a propósito.",
    example: "One red and one white can be a whole palette.",
    cognate: true,
  },
  {
    id: "typography",
    term: "typography",
    ipa: "ty-POG-ruh-fee",
    termEs: "tipografía",
    simple: "The craft of arranging letters. In a logo, letters become a picture.",
    simpleEs: "El arte de ordenar las letras.",
    example: "A heavy, tight wordmark can feel strong.",
    cognate: true,
  },
  {
    id: "typeface",
    term: "typeface",
    ipa: "TYPE-face",
    termEs: "tipo de letra",
    simple: "A family of letters that share a design, like a serif or a sans.",
    simpleEs: "Una familia de letras que comparten un diseño.",
    example: "A script typeface feels different from a blocky one.",
  },
  {
    id: "clear-space",
    term: "clear space",
    ipa: "kleer space",
    termEs: "zona de respeto",
    simple: "The empty margin around a logo so nothing crowds it.",
    simpleEs: "El margen vacío alrededor de un logo.",
    example: "Keep a logo away from photos, buttons, and other words.",
  },
  {
    id: "recognition",
    term: "recognition",
    ipa: "rek-ug-NISH-un",
    termEs: "reconocimiento",
    simple: "How fast a person knows the mark. Good logos are recognized in a glance.",
    simpleEs: "Qué tan rápido una persona conoce la marca.",
    example: "You can name some logos from the silhouette alone.",
    cognate: true,
  },
  {
    id: "critique",
    term: "critique",
    ipa: "krih-TEEK",
    termEs: "crítica",
    simple: "A careful talk about what a design is doing — not a mean comment about a person.",
    simpleEs: "Una conversación cuidadosa sobre lo que hace un diseño.",
    example: "In critique we say, 'The type is hard to read at small sizes.'",
    cognate: true,
  },
  {
    id: "silhouette",
    term: "silhouette",
    ipa: "sil-oo-ET",
    termEs: "silueta",
    simple: "The outline filled in as a solid shape, with no inside details.",
    simpleEs: "El contorno relleno como una forma sólida.",
    example: "If a logo fails as a silhouette, it may be too busy.",
    cognate: true,
  },
  {
    id: "hierarchy",
    term: "hierarchy",
    ipa: "HY-uh-rar-kee",
    termEs: "jerarquía",
    simple: "What you notice first, second, and third. Size and contrast create it.",
    simpleEs: "Qué notas primero, segundo y tercero.",
    example: "The symbol is large; the tagline is small.",
    cognate: true,
  },
  {
    id: "identity",
    term: "visual identity",
    ipa: "eye-DEN-tih-tee",
    termEs: "identidad visual",
    simple: "The system of logo, type, and color used over and over so the brand feels like itself.",
    simpleEs: "El sistema de logo, tipo y color que se usa una y otra vez.",
    example: "The identity is bigger than one sticker.",
    cognate: true,
  },
];

export function getTerm(id: string) {
  return GLOSSARY.find((t) => t.id === id);
}
