/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as LessonsIdRouteImport } from './routes/lessons/$id'
import { Route as PrintablesIndexRouteImport } from './routes/printables/index'
import { Route as PrintablesIdRouteImport } from './routes/printables/$id'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioIdRouteImport } from './routes/studio/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintablesIndexRoute = PrintablesIndexRouteImport.update({
  id: '/printables/',
  path: '/printables/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintablesIdRoute = PrintablesIdRouteImport.update({
  id: '/printables/$id',
  path: '/printables/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/score': typeof ScoreRoute
  '/teacher': typeof TeacherRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/printables/$id': typeof PrintablesIdRoute
  '/studio/$id': typeof StudioIdRoute
  '/lessons/': typeof LessonsIndexRoute
  '/printables/': typeof PrintablesIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/score': typeof ScoreRoute
  '/teacher': typeof TeacherRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/printables/$id': typeof PrintablesIdRoute
  '/studio/$id': typeof StudioIdRoute
  '/lessons': typeof LessonsIndexRoute
  '/printables': typeof PrintablesIndexRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/score': typeof ScoreRoute
  '/teacher': typeof TeacherRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/printables/$id': typeof PrintablesIdRoute
  '/studio/$id': typeof StudioIdRoute
  '/lessons/': typeof LessonsIndexRoute
  '/printables/': typeof PrintablesIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glossary'
    | '/score'
    | '/teacher'
    | '/lessons/$id'
    | '/printables/$id'
    | '/studio/$id'
    | '/lessons/'
    | '/printables/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glossary'
    | '/score'
    | '/teacher'
    | '/lessons/$id'
    | '/printables/$id'
    | '/studio/$id'
    | '/lessons'
    | '/printables'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/glossary'
    | '/score'
    | '/teacher'
    | '/lessons/$id'
    | '/printables/$id'
    | '/studio/$id'
    | '/lessons/'
    | '/printables/'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlossaryRoute: typeof GlossaryRoute
  ScoreRoute: typeof ScoreRoute
  TeacherRoute: typeof TeacherRoute
  LessonsIdRoute: typeof LessonsIdRoute
  PrintablesIdRoute: typeof PrintablesIdRoute
  StudioIdRoute: typeof StudioIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  PrintablesIndexRoute: typeof PrintablesIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printables/': {
      id: '/printables/'
      path: '/printables'
      fullPath: '/printables/'
      preLoaderRoute: typeof PrintablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printables/$id': {
      id: '/printables/$id'
      path: '/printables/$id'
      fullPath: '/printables/$id'
      preLoaderRoute: typeof PrintablesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlossaryRoute: GlossaryRoute,
  ScoreRoute: ScoreRoute,
  TeacherRoute: TeacherRoute,
  LessonsIdRoute: LessonsIdRoute,
  PrintablesIdRoute: PrintablesIdRoute,
  StudioIdRoute: StudioIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  PrintablesIndexRoute: PrintablesIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
